config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resource 'calendar', only: :show
end

app/models/area_days.rb
require 'csv'
require 'uri'
require 'open-uri'

class AreaDays
  class NotFound < StandardError; end

  AREA_COLUMN_NAME = "地名"
  CENTER_COLUMN_NAME = "センター"

  include Enumerable
  include Mem

  def initialize(url)
    @url = url
  end

  def find(area)
    csv.detect {|row|
      row[AREA_COLUMN_NAME] == area
    } or raise NotFound, "地名「#{area}」がurl「#{url}」で見つかりませんでした。"
  end

  def each
    csv.each do |row|
      yield row
    end
  end

  def url
    URI.join(@url, 'data/area_days.csv').to_s
  rescue
    @url
  end
  memoize :url

  private

  def csv
    CSV.parse(csv_content, headers: :first_row)
  end
  memoize :csv

  def csv_content
    response = OpenURI.open_uri(url)

    if response.status == ["200", "OK"]
      response.read
    else
      ""
    end
  rescue
    ""
  end
  memoize :csv_content
end

app/models/calendar.rb
class Calendar
  JA2EN_DAY_TABlE = %w(日 月 火 水 木 金 土).zip(%w(SU MO TU WE TH FR SA)).to_h

  include Mem

  def initialize(area_days)
    @area_days = area_days
  end

  def calname
    @area_days[AreaDays::AREA_COLUMN_NAME]
  end
  memoize :calname

  def to_s
    cal = Icalendar::Calendar.new
    cal.append_custom_property('X-WR-CALNAME;VALUE=TEXT', calname)
    cal.timezone do |t|
      t.tzid = tzid
      t.standard do |s|
        s.tzoffsetfrom = tzoffsetfrom
        s.tzoffsetto   = tzoffsetto
        s.tzname       = tzname
        s.dtstart      = dtstart
      end
    end
    events.each do |summary, days|
      cal.event do |e|
        e.dtstart     = Icalendar::Values::Date.new('20141201')
        e.summary     = summary
        e.rrule       = rrule(days)
      end
    end
    cal.publish
    cal.to_ical
  end

  private

  def events
    # FIXME: センターに対応したい
    @area_days.reject {|k, _|
      k == AreaDays::AREA_COLUMN_NAME || k == AreaDays::CENTER_COLUMN_NAME
    }
  end
  memoize :events

  def dtstart
    Time.at(0).utc.strftime("%Y%m%dT%H%M%S")
  end

  def tzid
    Time.zone.tzinfo.identifier
  end

  def tzname
    Time.zone.now.strftime("%Z")
  end

  def tzoffsetfrom
    Time.zone.now.strftime("%z")
  end

  alias tzoffsetto tzoffsetfrom

  def rrule(days)
    byday = days.split.map {|day|
      nth = day[1].try(:to_i).try(:nonzero?)
      "#{nth}#{JA2EN_DAY_TABlE[day[0]]}"
    }.join(?,)
    "FREQ=MONTHLY;BYDAY=#{byday}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: 'request.format == :js' # for embed
  before_action :confirm_site_domain, unless: 'request.format == :js'
  before_action :current_area_days, if: 'request.format == :ics'
  def show
    respond_to do |format|
      format.ics do
        filename = ERB::Util.url_encode("#{current_calendar.calname}.ics")
        send_data(current_calendar.to_s, filename: filename)
      end
      format.html do
        @area_days = area_days
      end
      format.js
    end
  end

  private

  def current_calendar
    @current_calendar ||= Calendar.new(current_area_days)
  end

  def area_days
    AreaDays.new(params[:site])
  end

  def current_area_days
    @current_area_days ||= area_days.find(params[:area]).to_h
  rescue AreaDays::NotFound => e
    flash.alert = e.message
    redirect_to root_path
  end

  def confirm_site_domain
    valid_site_domain = Resolv::DNS::Name.create("5374.jp")
    site_domain = Resolv::DNS::Name.create(URI.parse(params[:site]).host) rescue nil

    return if site_domain.try(:subdomain_of?, valid_site_domain)

    flash.alert = <<-NOTICE.strip_heredoc
      5374.jpのサブドメインのウェブサイトにのみ対応しています。
      指定されたウェブサイトのURL「#{params[:site]}」
    NOTICE
    redirect_to root_path(site: params[:site])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/show.html.erb
<h2>5374ウェブサイト:</h2>
<%= link_to params[:site], params[:site] %>
<h2>このページのURL:</h2>
<%= link_to calendar_url(site: params[:site]), calendar_url(site: params[:site]) %>
<h2>iCalウィジェット:</h2>
<%= render 'refills/browser' %>
<p class="description">あなたの5374の<code>index.html</code>の<code>body</code>の終了タグの手前、<code>script</code>タグの末尾に貼ってください。</p>
<textarea>
  <%= link_to 'iCal', calendar_url(site: params[:site]), class: 'cal5374 btn btn-default', data: {title: 'iCal', site: params[:site], ics: calendar_url(format: :ics)} %>
  <%= javascript_include_tag calendar_url(format: :js) %>
</textarea>
<h3>例:</h3>
<pre>
<code>
(前略)

  &lt;/script&gt;
  <%= link_to('iCal', calendar_url(site: params[:site]), class: 'cal5374 btn btn-default', data: {title: 'iCal', site: params[:site], ics: calendar_url(format: :ics)}).to_str %>
  <%= link_to(javascript_include_tag calendar_url(format: :js)).to_str %>
&lt;/body&gt;

(後略)
</code>
</pre>
<br/>
<h2>iCalダウンロード</h2>
<% if @area_days.any? %>
  <table>
    <tr>
      <th>地名</th>
    </tr>
  <% @area_days.each do |area_days| %>
    <tr>
      <td><%= link_to(area_days[AreaDays::AREA_COLUMN_NAME], calendar_url(format: :ics, site: params[:site], area: area_days[AreaDays::AREA_COLUMN_NAME])) %></td>
    </tr>
  <% end %>
  </table>
<% else %>
<div class="flash-alert">
  <span><%= link_to('CSV', @area_days.url) %>の中に地域の情報が見つかりません。</span>
</div>
<% end %>

app/views/home/index.html.erb
<%= render 'shared/flash' %>
<%= render 'refills/device' %>
<p class="note">
※現在、センターに対応しておりません。<br/>
ご不明な点や問題がございましたら<a href="https://github.com/CodeforOkinawa/cal5374/issues">GitHubのissueページ</a>でご報告くださると助かります。
<br/>
ソースコードは<a href="https://github.com/CodeforOkinawa/cal5374">CodeforOkinawa/cal5374</a>にて公開されております。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cal5374</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <h1><%= link_to('Cal5374', root_path) %></h1>
  <hr/>
  <%= yield %>
</div>
</body>
</html>

app/views/refills/_browser.html.erb
<div class = "browsers">
  <div class = "browser">
    <div class="browser-top-bar">
      <div class="browser-circle"></div>
      <div class="browser-circle"></div>
      <div class="browser-circle"></div>
    </div>
    <div class="browser-content">
    </div>
  </div>
</div>

<div class="cover"></div>

app/views/refills/_device.html.erb
<div class="device-background">
  <div class="device-text">
    <h4>ゴミ収集日をいつものカレンダーへ</h4>
    <p><a href="http://5374.jp">5374.jp</a>で提供されているゴミ収集日をスマホ/PCで使えるカレンダーのスケジュールに変換するサービスです。</p>
    <%= form_tag calendar_path, method: :get do %>
    <%= label_tag :site, "5374ウェブサイトのURL:" %>
    <%= url_field_tag :site, params[:site], placeholder: '例: http://naha.5374.jp', required: true %>
    <%= submit_tag '5374をiCal形式に変換' %>
    <% end %>
  </div>
  <div class="device">
    <div class="screen"></div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
<div class="flash-<%= type %>">
  <span><%= message %></span>
</div>
<% end %>